### ISSUE TITLE
private

### ISSUE THREAD

**Issue by stgm** [FrankHouweling/Mobiele-Studiegids-Uva#1]
Je moet je repo nog even private maken!
Eventueel een edu account aanvragen op http://github.com/edu

**Comment by FrankHouweling** [comment]
Edu aangevraagd: nu alleen nog afwachten!

**Comment by stgm** [comment]
Nog niet gedaan dus reopend.

**Comment by FrankHouweling** [comment]
Ik krijg geen edu; is openbaar echt een groot probleem?

**Comment by stgm** [comment]
Wat betekent "ik krijg geen edu"? Krijg je geen antwoord? Misschien in de comments bij de aanvraag even echt zetten voor welke cursus enzo.

En ja ik wil dat je het private maakt.
