### ISSUE TITLE
push/pull repository

### ISSUE THREAD

**Issue by mauii93** [FrankHouweling/Mobiele-Studiegids-Uva#2]
hoi Martijn.

Het lukt nog steeds niet helemaal om mijn bestanden te pushen naar Frank. Als ik git push doe, dan pusht hij mijn veranderingen naar mijn lab1 repository. Het liefst wil ik in vhosts gewoon het lab1 met BlogIgniter voor mijn eigen repository (lab1) gebruiken en voor project0 wil ik dat hij gepusht wordt naar onze gezamenlijke repository. Heb al vanalles geprobeerd, maar lukt nog niet... Heb jij enig idee?

Gr. Maurice.

**Comment by stgm** [comment]
Ja, je moet de map op je eigen computer (of op de appliance) koppelen aan de juiste repo op github.

Ga in de map staan die je wil koppelen.
git remote rm origin <-- haalt koppeling "origin" weg
git remote add origin URL  <-- zet juiste koppeling erin

Groeten,
Martijn

**Comment by mauii93** [comment]
Hij doet het! dankjewel. Nu kan ik lekker aan de gang ;)

Fijn weekend.

Groeten,
Maurice

Op 3 mrt. 2012, om 08:15 heeft Martijn Stegeman het volgende geschreven:
